"""initial schema

Revision ID: 3ad09fb566ed
Revises:
Create Date: 2026-08-24 15:45:22.116580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3ad09fb566ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("key IN ('script2assets', 'script2shots', 'zimage', 'minimaxh3')", name='ck_prompt_templates_key'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_prompt_templates_key')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prompt_fragment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_styles_name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed', 'canceled')", name='ck_tasks_status'),
    sa.CheckConstraint("type IN ('gen_assets', 'gen_shots', 'gen_asset_image', 'gen_clip_video')", name='ck_tasks_type'),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name='ck_tasks_progress'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_tasks_active_request_id', 'tasks', ['request_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running') AND request_id IS NOT NULL"))
    op.create_index('uq_tasks_active_target', 'tasks', ['type', 'target_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running') AND type IN ('gen_assets', 'gen_shots')"))
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('image_prompt_cache', sa.Text(), nullable=True),
    sa.Column('image_prompt_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('generated', 'manual')", name='ck_assets_source'),
    sa.CheckConstraint("type IN ('character', 'scene', 'prop')", name='ck_assets_type'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('script_revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('assets_generated_script_revision', sa.Integer(), nullable=True),
    sa.Column('shots_generated_script_revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'seq', name='uq_episodes_project_seq')
    )
    op.create_table('asset_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('built_prompt', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('generated', 'uploaded')", name='ck_asset_images_source'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_asset_images_current', 'asset_images', ['asset_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('clips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('generation_mode', sa.String(), server_default=sa.text("'ref2v'"), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('requested_duration', sa.Integer(), nullable=False),
    sa.Column('prompt_cache', sa.Text(), nullable=True),
    sa.Column('prompt_input_hash', sa.Text(), nullable=True),
    sa.Column('generation_state', sa.String(), server_default=sa.text("'empty'"), nullable=False),
    sa.Column('freshness', sa.String(), server_default=sa.text("'fresh'"), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("freshness IN ('fresh', 'stale')", name='ck_clips_freshness'),
    sa.CheckConstraint("generation_mode IN ('ref2v', 'fl2v', 'context_loop')", name='ck_clips_generation_mode'),
    sa.CheckConstraint("generation_state IN ('empty', 'queued', 'generating', 'ready', 'failed')", name='ck_clips_generation_state'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('duration_est', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('shot_type', sa.String(), nullable=False),
    sa.Column('camera', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('normal', 'changed')", name='ck_shots_status'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'order_index', name='uq_shots_episode_order_index')
    )
    op.create_table('clip_ref_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_name_snapshot', sa.String(), nullable=False),
    sa.Column('asset_type_snapshot', sa.String(), nullable=False),
    sa.Column('override_image_path', sa.Text(), nullable=True),
    sa.Column('override_sha256', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('slot_no >= 1 AND slot_no <= 9', name='ck_clip_ref_slots_slot_no'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clip_id', 'slot_no', name='uq_clip_ref_slots_clip_slot')
    )
    op.create_table('clip_shots',
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('clip_id', 'shot_id'),
    sa.UniqueConstraint('clip_id', 'position', name='uq_clip_shots_position'),
    sa.UniqueConstraint('shot_id', name='uq_clip_shots_shot')
    )
    op.create_table('clip_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('requested_duration', sa.Integer(), nullable=False),
    sa.Column('actual_duration', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('built_prompt', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_clip_videos_current', 'clip_videos', ['clip_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('shot_assets',
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('shot_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shot_assets')
    op.drop_index('uq_clip_videos_current', table_name='clip_videos', postgresql_where=sa.text('is_current = true'))
    op.drop_table('clip_videos')
    op.drop_table('clip_shots')
    op.drop_table('clip_ref_slots')
    op.drop_table('shots')
    op.drop_table('clips')
    op.drop_index('uq_asset_images_current', table_name='asset_images', postgresql_where=sa.text('is_current = true'))
    op.drop_table('asset_images')
    op.drop_table('episodes')
    op.drop_table('assets')
    op.drop_table('projects')
    op.drop_index('uq_tasks_active_target', table_name='tasks', postgresql_where=sa.text("status IN ('queued', 'running') AND type IN ('gen_assets', 'gen_shots')"))
    op.drop_index('uq_tasks_active_request_id', table_name='tasks', postgresql_where=sa.text("status IN ('queued', 'running') AND request_id IS NOT NULL"))
    op.drop_table('tasks')
    op.drop_table('styles')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
